services:
  configuration:
    class: Infrastructure\Kernel\Configuration

  session:
    class: Infrastructure\Data\Session

  cookie:
    class: Infrastructure\Data\Cookie

  file:
    class: Infrastructure\File\Service\FileService

  email:
    class: Infrastructure\Email\Service\EmailService
    arguments: ["@configuration"]
