routes:
  -
    name: test
    url: /teste
    controller: App\Controller\Test\TestController
    action.result: testAction
    method: ["post", "get"]

  - name: userCreate
    url: /user/new
    controller: App\Controller\User\UserController
    action.result: createAction
    method: ["post", "get"]

  - name: userGetAll
    url: /users
    controller: App\Controller\User\UserController
    action.result: getAllAction
    method: ["get"]

  - name: userGetById
    url: /user
    controller: App\Controller\User\UserController
    action.result: getByIdAction
    method: ["get"]
