routes:
  -
    name: index
    url: /
    controller: App\Controller\IndexController
    action.result: indexAction
    method: ["post", "get"]
  -
    name: translateJs
    url: /util/language/translate.js
    controller: App\Controller\Util\UtilController
    action.result: translateJsAction
    method: ["get"]
  -
    name: getUrlJs
    url: /util/url/url.js
    controller: App\Controller\Util\UtilController
    action.result: getUrlJsAction
    method: ["get"]
  -
    name: test
    url: /teste
    controller: App\Controller\Test\TestController
    action.result: testAction
    method: ["post", "get"]
  -
    name: exampleFileUpload
    url: /example/file/upload
    controller: App\Controller\Example\FileExampleController
    action.result: exampleUploadAction
    method: ["post", "get"]
  -
    name: fileUpload
    url: /file/upload
    controller: App\Controller\File\FileController
    action.result: uploadAction
    method: ["post"]

  - name: logoff
    url: /logoff
    controller: App\Controller\Auth\AuthController
    action.result: logoffAction
    method: ["post", "get"]

  - name: login
    url: /login
    controller: App\Controller\Auth\AuthController
    action.result: loginAction
    method: ["post", "get"]

  - name: auth
    url: /auth
    controller: App\Controller\Auth\AuthController
    action.result: authAction
    method: ["post", "get"]

  - name: forgotPassword
    url: /forgot/password
    controller: App\Controller\Auth\AuthController
    action.result: forgotPasswordAction
    method: ["get"]

  - name: sendForgotPassword
    url: /forgot/password/send
    controller: App\Controller\Auth\AuthController
    action.result: sendNewPasswordOfForgotPasswordAction
    method: ["post"]

  - name: dashboard
    url: /dashboard
    controller: App\Controller\Dashboard\DashboardController
    action.result: indexAction
    method: ["get"]

  - name: userCreate
    url: /user/new
    controller: App\Controller\User\UserController
    action.result: createAction
    method: ["post", "get"]

  - name: userGetAll
    url: /users
    controller: App\Controller\User\UserController
    action.result: getAllAction
    method: ["get"]

  - name: userGetById
    url: /user
    controller: App\Controller\User\UserController
    action.result: getByIdAction
    method: ["get"]
