routes:
  -
    name: test
    url: /teste
    controller: App\Controller\Test\TestController
    action.result: testAction
    method: ["post", "get"]

  - name: logoff
    url: /logoff
    controller: App\Controller\Auth\AuthController
    action.result: logoffAction
    method: ["post", "get"]

  - name: login
    url: /login
    controller: App\Controller\Auth\AuthController
    action.result: loginAction
    method: ["post", "get"]

  - name: userCreate
    url: /user/new
    controller: App\Controller\User\UserController
    action.result: createAction
    method: ["post", "get"]

  - name: userGetAll
    url: /users
    controller: App\Controller\User\UserController
    action.result: getAllAction
    method: ["get"]

  - name: userGetById
    url: /user
    controller: App\Controller\User\UserController
    action.result: getByIdAction
    method: ["get"]
